name: Build and Release Firefox Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install web-ext

      - name: Build the extension
        run: web-ext build --artifacts-dir build

      - name: Release the extension
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}
          draft: false
          prerelease: false